// Regenerates database/schema.sql and database/seed.sql (for manual import via phpMyAdmin).
// Run: npm run db:sql
process.env.DB_CLIENT = 'sqlite'
process.env.SQLITE_FILE = ':memory:'
const fs = require('fs')
const path = require('path')
const db = require('../server/db')

const esc = v => v == null ? 'NULL'
  : typeof v === 'number' ? String(v)
  : "'" + String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '\\r') + "'"

;(async () => {
  const out = path.join(__dirname, '..', 'database')
  fs.mkdirSync(out, { recursive: true })
  const header = '-- Generated by tools/generate-sql.js — do not edit by hand.\nSET NAMES utf8mb4;\n\n'
  fs.writeFileSync(path.join(out, 'schema.sql'), header + db.ddl('mysql').join('\n\n') + '\n')

  await db.ensureSchema()
  let sql = header
  for (const table of ['settings', 'menu_items', 'sections', 'section_items']) {
    const rows = await db.query(`SELECT * FROM ${table}`)
    if (!rows.length) continue
    const cols = Object.keys(rows[0])
    sql += `INSERT INTO ${table} (${cols.join(', ')}) VALUES\n` +
      rows.map(r => '(' + cols.map(c => esc(r[c])).join(', ') + ')').join(',\n') + ';\n\n'
  }
  fs.writeFileSync(path.join(out, 'seed.sql'), sql)
  await db.close()
  console.log('Wrote database/schema.sql and database/seed.sql')
})()
